### ISSUE TITLE
Could not get the storage format of the medium

### ISSUE THREAD

**Issue by Bryce-L** [mwrock/packer-templates#14]
I'm following a Chef tutorial (https://learn.chef.io/local-development/windows/get-set-up/get-set-up-vagrant/) and ran into a problem.  It looks like Virtual Box is throwing an error when trying to attach the iso:

==> virtualbox-iso: Error attaching ISO: VBoxManage error: VBoxManage.exe: error: Could not get the storage format of the medium 'C:\iso\9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.iso' (VERR_NOT_SUPPORTED)

I'm using:
- VBoxManage.exe version 5.04r102546
- Packer.exe version 0.8.6

See my comment on Chef for more details: https://learn.chef.io/local-development/windows/get-set-up/get-set-up-vagrant/#comment-2280143771

**Comment by mwrock** [comment]
do you have the modified template you used by chance and mind sharing it?

**Comment by Bryce-L** [comment]
Here are the contents of my vbox-2012r2.json file:

{
    "builders": [{
    "type": "virtualbox-iso",
    "vboxmanage": [
      [ "modifyvm", "{{.Name}}", "--natpf1", "guest_winrm,tcp,,55985,,5985" ],
      [ "modifyvm", "{{.Name}}", "--memory", "2048" ],
      [ "modifyvm", "{{.Name}}", "--vram", "36" ],
      [ "modifyvm", "{{.Name}}", "--cpus", "2" ]
    ],
    "guest_os_type": "Windows2012_64",
    "iso_url": "{{ user `iso_url` }}",
    "iso_checksum": "{{ user `iso_checksum` }}",
    "iso_checksum_type": "md5",
    "communicator": "winrm",
    "winrm_username": "vagrant",
    "winrm_password": "vagrant",
    "winrm_port": "55985",
    "winrm_timeout": "6h",
    "guest_additions_mode": "disable",
    "shutdown_command": "C:/windows/system32/sysprep/sysprep.exe /generalize /oobe /unattend:C:/Windows/Panther/Unattend/unattend.xml /quiet /shutdown",
    "shutdown_timeout": "15m",
    "floppy_files": [
      "answer_files/2012_r2{{user `core`}}/Autounattend.xml",
      "scripts/postunattend.xml",
      "scripts/boxstarter.ps1",
      "scripts/package.ps1"
    ]
  }],
    "post-processors": [
    {
      "type": "vagrant",
      "keep_input_artifact": true,
      "output": "windows2012r2min-{{.Provider}}.box",
      "vagrantfile_template": "vagrantfile-windows.template"
    }
  ],
  "variables": {
    "core": "",
    "iso_checksum": "773ea2d712c7c6f09b99c3b2b6e0eeb9",
    "iso_url": "C:/iso/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO"
  }
}

**Comment by mwrock** [comment]
I am guessing something went wrong in your download. This has happened to me before. I downloaded the latest ISO but got a different checksum than you and did not have an issue.

I just pushed an update to the template that uses the HTTP ISO URL by default. Using this, packer will download the ISO over http and users wont have to worry about where to put the ISOs. It will cache them across runs so it wont need to download again. However, whenever MS rotates the downloads, the url will need to be changed.

**Comment by sajenjeshan1222** [comment]
i too have  a same problem what can i do for it can any one solve my problem ??????????????

**Comment by mwrock** [comment]
Might try deleting and redownloading the iso. It may be corrupt.

**Comment by Rupesh-klr** [comment]
How did the issues is solved ?

**Comment by kasaiee** [comment]
I tried several times to redownloading file but the error not solved!
